### ISSUE TITLE
Tree?

### ISSUE THREAD

**Issue by samhamm** [codefellows/code-201-prework#71]
Mac users install it, Win/Lin do not. Remedy?

**Comment by michaeltreat** [comment]
For Ubuntu/ Windows users are running with WSL then they can type `sudo apt install tree`.

For Windows only there is an obscure doc I made in the history of this repo which points to a program that can be installed giving the tree option to Git bash. I will see if I can find it again. 

Also, Windows Powershell has tree functionality installed by default. This doesn't help with the Git Bash terminal, but if a student is choosing to not use WSL, then learning to use Powershell would be helpful for them regardless.

**Comment by michaeltreat** [comment]
Here are the instructions for getting tree setup for Windows user's not using WSL, and who are not using the Powershell. I haven't used this since I last updated it though, but a quick look over it looks good.

https://github.com/codefellows/code-201-prework/blob/cd0ceb288ebf44dc260d8dcc45aeef4a3a1ec3c4/prework/windows/4_install_tree.md

**Comment by samhamm** [comment]
Thanks, @michaeltreat!
