### ISSUE TITLE
Npm Pathing for WSL users.

### ISSUE THREAD

**Issue by michaeltreat** [codefellows/code-201-prework#77]
For issues with NPM Pathing, please [look here](https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide/issues/7) for reference and possible solutions first. 

If the link does not provide a fix for you, please leave a comment or create an issue!

Thanks.

Synopsis from Link:

> "Pathing from Windows FS to Linux FS is not hierarchical, breaking NPM's functionality when it tries to use globally installed packages on the Windows FS. As such, it is recommend to add a package.json to a top-level directory at or directly up the tree from where all coding work is held. This will allow you to install packages at this level to act as the Windows global package install location. This also requires navigating to that top-level directory when you wish to install something globally on the Windows FS, as the -g flag would install it on the Linux side."

**Comment by bradsmialek** [comment]
Possible solutions [here](https://stackoverflow.com/questions/40566348/maximum-call-stack-size-exceeded-on-npm-install) and [here](https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide/issues/7).
This issue is open here: [[P0][Concept][Content] NPM pathing with WSL #7](https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide/issues/7)
