### ISSUE TITLE
Vague Prework task 2. Ensure your laptop up to the task of coding

### ISSUE THREAD

**Issue by ncarignan** [codefellows/code-201-prework#79]
This task contains vague requirements with no instructions and should be more specific.
What is the minimum hard drive space and memory?
Should we define memory?
How do they eliminate viruses and can we recommend any programs?

References https://github.com/codefellows/code-101-prework/issues/75

**Comment by samhamm** [comment]
From CF site: 

Material Requirements
You are required to supply your own laptop that meets the below requirements. Chromebooks are not suitable for this course, since you can’t directly control installed software. Most students use Macs. You are responsible for the upkeep and maintenance of your computer throughout the course. The course pre-work will have specific instructions for configuring your computer to be ready for the first day of class.

64-bit Operating System, like macOS or Windows 10.
Fully up to date, with the latest version of the operating system and all security updates installed.
At least 50GB of free space on the hard drive.
At least 8GB of RAM. 16GB RAM strongly preferred.
Free of viruses, and in general working order.

**Comment by samhamm** [comment]
https://www.codefellows.org/courses/code-201/foundations-of-software-development/#material-requirements

THAT IS THE MAGIC SAUCE

**Comment by ncarignan** [comment]
lgtm
