### ISSUE TITLE
WSL `npm` setup issue

### ISSUE THREAD

**Issue by brookr** [codefellows/code-201-prework#91]
From Erin, working with Code 301 students in Class 1: 

> We have had 3 students get max call stack errors when running npm install using the provided package.json from the lab-00d starter code. They were all WSL/Ubuntu configuration computers. We were able to solve the problem by NOT using the provided package.json and instead deleting all node_modules (from the repo) and doing an npm init instead (and manually adding the test scripts from the provided package.json). After this we were able to run an npm install like normal.

**Comment by bradsmialek** [comment]
Without seeing the specific example, there still doesn't seem to be a clearly defined solution for this issue in any of the resources I've searched.  Erin's solution above worked and it seems [stackoverflow](https://stackoverflow.com/questions/40566348/maximum-call-stack-size-exceeded-on-npm-install) also has similar solutions that have worked.  
For additional information, the issue is still being addressed [here](https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup-Guide/issues/7).
